apiVersion: v1
kind: ConfigMap
metadata:
  name: casperparser-config-{{ .Values.casperNetwork }}
data:
  CASPER_PARSER_REDIS: {{ include "casperparser.redis.addr" . | quote }}
  CASPER_PARSER_RPC: {{ .Values.casperparser.rpc | quote }}
  CASPER_PARSER_DATABASE: "{{ include "casperparser.postgres.addr" . }}?sslmode=disable"
  CASPER_PARSER_EVENT: {{ .Values.casperparser.events }}
{{- if .Values.postgrest.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgrest-config-{{ .Values.casperNetwork }}
data:
  PGRST_DB_URI: "{{ include "casperparser.postgres.addr" . }}"
  PGRST_DB_SCHEMA: "public"
  PGRST_DB_ANON_ROLE: "web_anon"
  PGRST_OPENAPI_MODE: "ignore-privileges"
  PGRST_OPENAPI_SERVER_PROXY_URI: "https://{{ .Values.traefik.certmanager.domain }}/swagger"
  PGRST_DB_MAX_ROWS: "{{ .Values.postgrest.maxRows }}"
{{- end }}
{{- if .Values.postgres.enabled }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: max-conns
data:
  max_conns.sql: "ALTER SYSTEM SET max_connections = {{ .Values.postgres.maxConns }};"
{{- end }}