{{- if .Values.asynqmon.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: casperparser-metrics-{{ .Values.casperNetwork }}
  labels:
    k8s-apps: http
spec:
  jobLabel: k8s-app
  selector:
    matchExpressions:
      - {key: k8s-app, operator: Exists}
  namespaceSelector:
    matchNames:
      - casperparser-{{ .Values.casperNetwork }}
  endpoints:
    - port: http-metrics
      interval: 15s
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: casperparser-state-metrics-{{ .Values.casperNetwork }}
    k8s-app: casperparser-state-metrics-{{ .Values.casperNetwork }}
  annotations:
    alpha.monitoring.coreos.com/non-namespaced: "true"
  name: casperparser-state-metrics-{{ .Values.casperNetwork }}
spec:
  ports:
    - name: http-metrics
      port: {{ .Values.asynqmon.containerPort }}
      targetPort: {{ .Values.asynqmon.containerPort }}
      protocol: TCP
  selector:
    app: asynqmon-{{ .Values.casperNetwork }}
{{- end }}