apiVersion: v1
kind: PersistentVolume
metadata:
  name: casperparser-{{ .Values.casperNetwork }}-pg-volume
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  capacity:
    storage: {{ .Values.postgres.volume.size }}Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/casperparser-{{ .Values.casperNetwork }}-pg-volume/"