apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: casperparser-{{ .Values.casperNetwork }}-pg-volume
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.postgres.volume.size }}Gi