apiVersion: v1
kind: Service
metadata:
  name: postgrest-service-{{ .Values.casperNetwork }}
spec:
  ports:
    - name: web
      port: {{ .Values.postgrest.containerPort }}
      targetPort: {{ .Values.postgrest.containerPort }}
  selector:
    app: postgrest-{{ .Values.casperNetwork }}
status:
  loadBalancer: { }
---
apiVersion: v1
kind: Service
metadata:
  name: casperparser-db-service-{{ .Values.casperNetwork }}
spec:
  ports:
    - name: casperparser-db-service-{{ .Values.casperNetwork }}
      protocol: TCP
      port: {{ .Values.postgres.containerPort }}
      targetPort: {{ .Values.postgres.containerPort }}
  selector:
    app: casperparser-db-{{ .Values.casperNetwork }}
---
apiVersion: v1
kind: Service
metadata:
  name: casperparser-redis-service-{{ .Values.casperNetwork }}
spec:
  ports:
    - name: casperparser-redis-service-{{ .Values.casperNetwork }}
      protocol: TCP
      port: {{ .Values.redis.containerPort }}
      targetPort: {{ .Values.redis.containerPort }}
  selector:
    app: casperparser-redis-{{ .Values.casperNetwork }}
